<?php
 $_category=null;
 $found=false;
  $_categories=null;
?>
<?php if ($currentCategory=Mage::registry('current_category')) $found=true; ?>
<?php
   $id=0;
   $level=0;
   $currentId=0;
   if($currentCategory){
	  $ids=$currentCategory->getPathIds();
	  $level=count($ids)-1;
	  $id=(isset($ids[2])&&$ids[2]>0)?$ids[2]:0;
	  $currentId=$currentCategory->getId();
    }
if($id>0)
{
   $_category = Mage::getModel('catalog/category')->load($id);
   $_categories=$_category->getChildrenCategories();
}
?>
<?php if($_categories):?>
      <h2>CATEGORY</h2>
      <ul>
<?php foreach ($_categories as $category):?>
<?php $category = Mage::getModel('catalog/category')->load($category->getId()) ?>
        <li class="act">
        <a title="<?php echo $category->getName();?>" class="act" href="<?php echo $category->getUrl();?>"><?php echo $category->getName();?> </a>
        <?php if($level>=3 && $category->hasChildren() && in_array($category->getId(),$ids)) :?>
          <span class="arrow"></span>
          <ul>
            <?php foreach($category->getChildrenCategories() as $child) : ?>
            <?php $child = Mage::getModel('catalog/category')->load($child->getId()) ?>
            <li><a title="<?php echo $child->getName()?>" href="<?php echo $child->getUrl()?>" <?php echo ($child->getId()==$currentId)?'class="selected"':'';?>><?php echo $child->getName()?></a></li>
            <?php endforeach; ?>
          </ul> 
        <?php endif;?>
        </li>
<?php endforeach; ?>
      </ul>
<?php endif;?>
