<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="page-head">
    <h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="in-page">
    <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>

    <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', Mage::getUrl()) ?></p>
</div><br/><br/>
<script type="text/javascript">
    $j(document).ready(function (e) {
        mobileCart.registerSubmit('cart-form', '<?php echo $this->getUrl('awmobile/cart/updatePost') ?>');
        mobileCart.registerCoupon('discount-coupon-form', '<?php echo $this->getUrl('awmobile/cart/couponPost') ?>');
        mobileCart.registerGiftcard('giftcard-form', '<?php echo $this->getUrl('awmobile/cart/addGiftcard') ?>');
        mobileCart.contentUrl = '<?php echo $this->getUrl('awmobile/cart/content'); ?>';
    });
</script>