<?php
	$brands=$this->getBrands();
	$_helper=Mage::helper('brand');
?>
<?php if(!count($brands)): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	
	  <h1>Brands</h1>
	<?php
		$brandList=array();
		foreach($brands as $brand):
		$brandList[]=array('title'=>$brand['title'],'image'=>$brand['filename'],'url'=>$_helper->getUrl($brand['url']));
		endforeach;
	?>
 <div class="brands-sec">
	<ul class="brands-link">
	<?php
	foreach($brandList as $brand):
	?>
		<li>
		<a href="<?php echo $brand['url']?>" title="<?php echo $brand['title']?>"><?php echo $brand['title']?></a>
                   
		</li>
	<?php endforeach;?>
	</ul>
  </div>
  <div class="brands-images"> 

	<?php
        reset($brandList);
	foreach($brandList as $brand):
	?>

		  <a href="<?php echo $brand['url']?>" title="<?php echo $brand['title']?>">
		<img src="<?php echo '/media/'.$brand['image']?>" alt="<?php echo $brand['title']?>"/>
		</a>

	<?php endforeach;?>
  </div>
<?php endif;?>
