 <div class="newsletter-box ">
            <h4 class="default-img" >NEWSLETTER</h4>
            <p>Don't miss out on all things Western Chic!<br/>
              Subscribe to our newsletter and start receiving special deals, exclusive offers, and styling tips from Cowgirl Kim.</p>
            <div class="newsletter-search">
              <input type="text" value="" placeholder="Enter Your Email Address" id="footer_newsletter" name="email" autocomplete="off"/>
              <input name="btnNlSignup"  type="submit"  id="btnNlSignup" Value="Subscribe"/>
            </div>
            <div id="nsl_error" class="no-dispaly"></div>
          </div>

<script type="text/javascript">
//<![CDATA[
jQuery(function(){
	jQuery('#newsletter-box').cc({textId: "#footer_newsletter",
		   buttonId: "#btnNlSignup",
		   errorDivId:"#nsl_error",
		   fadeImgPath:"<?php echo $this->getSkinUrl('images/subscribe-btn.png')?>",
		   highlightImgPath:"<?php echo $this->getSkinUrl('images/subscribe-btn1.png')?>",
		   url:"<?php echo Mage::getUrl('constantcontact/index/subscribeVisitor')?>"
		   });
});
 //]]>
</script>
