<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->__("Dear %s", $this->getCustomer()->getName()); ?>,
<br/>
<?php echo $this->__("We would like to remind you that your") ?>
<a href="<?php echo Mage::getUrl('sarp/customer/view', array('id' => $this->getSubscription()->getId()))?>"><?php echo $this->__("subscription")?></a>
<?php echo $this->__("expires at %s.", $this->formatDate($this->getSubscription()->getDateExpire())) ?>
<br/>
<?php echo $this->__("To extend the subscription, please follow this") ?>
<a href="<?php echo Mage::getUrl('sarp/customer/view', array('id' => $this->getSubscription()->getId()))?>"><?php echo $this->__("link")?></a>.
