<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php foreach ($languages as $_code=>$_link): ?>
    <?php if($_link): ?>
        <a href="<?php echo $_link ?>"><img src="<?php echo $this->getSkinUrl('images/flag_<?php echo $_code ?>.gif') ?>" width="30" height="20" alt="<?php echo $_code ?>" /></a>
    <?php else: ?>
        <!--img src="<?php echo $this->getSkinUrl('images/flag_<?php echo $_code ?>.gif') ?>" width="30" height="20" alt="<?php echo $_code ?>"/-->
    <?php endif; ?>
<?php endforeach; ?>
