<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (Mage::helper('sarp')->extensionEnabled('AW_Deliverydate')): ?>
<?php echo Mage::app()->getLayout()->createBlock('deliverydate/frontend_checkout_onepage_deliverydate', 'deliverydate', array('template' => "aw_deliverydate/checkout/onepage/shipping_method/deliverydate.phtml"))->toHtml(); ?>
<?php echo Mage::app()->getLayout()->createBlock('core/html_calendar', 'deliverydate_cal', array('template' => "page/js/calendar.phtml"))->toHtml(); ?>
<?php else: ?>
<?php if (Mage::getStoreConfig(AW_Sarp_Helper_Config::XML_PATH_APPEARANCE_SHOW_POSTMAN_NOTICE)): ?>
    <dl>
        <dt class="input-box">
            <strong><?php echo $this->__("Delivery Notice");?></strong>
        </dt>
        <dd><textarea name="aw_sarp_postman_notice" cols="64"
                      rows="10"><?php //echo Mage::getSingleton('customer/session')->getPostmanNotice()?></textarea>
        </dd>
    </dl>
    <?php endif; ?>
<?php endif; ?>

