<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><p><?php echo $this->getMethod()->getTitle() ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?><br /><?php echo $this->__('Make Check payable to: %s', $this->htmlEscape($this->getPayableTo())) ?><?php endif; ?>
    <?php if($this->getMailingAddress()): ?>
        <br /><?php echo Mage::helper('payment')->__('Send Check to:') ?>
        <br />
        <span class="checkmo-mailing-address">
            <?php echo nl2br($this->htmlEscape($this->getMailingAddress())) ?>
        </span>
    <?php endif; ?>
<?php endif; ?>
</p>
