<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $subscription = $this->getSubscription() ?>
<?php if ($subscription->getProduct()->getAwSarpEnabled()): ?>

<p class="sarp-subscription">
    <?php echo $this->__('Subscription type') ?>:

    <?php if (($types = $subscription->getSubscriptionTypes()) && (sizeof($types) > 1)): ?>

    <select name="aw_sarp_subscription_type" style="width:200px;">
        <?php foreach ($types as $item): ?>
        <option value="<?php echo $item['value']?>"><?php echo $item['label']?></option>
        <?php endforeach; ?>
    </select>
    <?php elseif ($types && (count($types) == 1)): ?>
    <span><input type="hidden" name="aw_sarp_subscription_type"
                 value="<?php echo $types[0]['value']?>"/><?php echo $types[0]['label']?></span>
    <?php endif;?>
</p>

<?php endif; ?>