<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="account-box ad-tags">
    <div class="head">
            <h4><?php echo $this->__('My Recent Tags') ?></h4>
            <a href="<?php echo $this->getAllTagsUrl() ?>"><?php echo $this->__('View All Tags') ?></a>
    </div>
    <ol>
        <?php $iterator = 0 ?>
        <?php foreach( $this->getCollection()->getItems() as $_item ): ?>
            <li<?php if($iterator % 2 == 0): ?> class="odd"<?php else: ?> class="even"<?php endif; ?>>
                <div class="count"><?php echo ++$iterator ?></div>
                <div class="content">
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a><br/>
                    <strong><?php echo $this->__('Tags:') ?></strong>
                        <?php $_i = 0; ?>
                        <?php foreach( $_item->getProductTags() as $_tag ): ?>
                            <a href="<?php echo $_tag->getViewTagUrl() ?>"><?php echo $this->htmlEscape($_tag->getName()) ?></a><?php if(++$_i != sizeof($_item->getProductTags()->getItems())): ?>,<?php endif; ?>
                        <?php endforeach; ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
