<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-head">
    <h3><?php echo Mage::helper('contacts')->__('Contact Us') ?></h3>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <fieldset class="group-select">
        <h4 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h4>
        <ul id="contactus-fields-collection">
        <li>
            <div><label for="name"><?php echo Mage::helper('contacts')->__('Name') ?> <span class="required">*</span></label></div>
            <div class="input-box"><input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" placeholder="<?php echo Mage::helper('contacts')->__('Name *') ?>"  class="required-entry input-text" type="text" />
            </div>


                <div><label for="email"><?php echo Mage::helper('contacts')->__('Email') ?> <span class="required">*</span></label></div>
                <div class="input-box"><input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" placeholder="<?php echo Mage::helper('contacts')->__('Email Address *') ?>" class="required-entry input-text validate-email" type="text" />
                </div>

                <div class="clear"></div>

                
                <div><label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label></div>
                <div class="input-box"><input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" placeholder="<?php echo Mage::helper('contacts')->__('Telephone') ?>"/>
                </div>

	
		 <div class="clear"></div>
		<div><label for="order"><?php echo Mage::helper('contacts')->__('Order') ?></label></div>
            <div class="input-box"><input name="order" id="order" title="<?php echo Mage::helper('contacts')->__('Order') ?>" value"" placeholder="<?php echo Mage::helper('contacts')->__('Order #') ?>" class="input-text" type="text" />

            </div>
            
           <div class="clear"></div>
           <div><label for="question"><?php echo Mage::helper('contacts')->__('How Can We Help?') ?> <span class="required">*</span></label></div>
           <div class="input-box 1">
            <select name="question" id="question" class="input-select required-entry" style="width:100%; height:30px;">
		 <option value=""><?php echo Mage::helper('contacts')->__('Select One')?></option>
                <option value="1"><?php echo Mage::helper('contacts')->__('I have a general question?')?></option>
                <option value="2"><?php echo Mage::helper('contacts')->__('I have a question about my account?')?></option>
                <option value="3"><?php echo Mage::helper('contacts')->__('I have a question about my order?')?></option>
                <option value="4"><?php echo Mage::helper('contacts')->__('I have a technical website question?')?></option>    
            </select>
           </div>	
		


                <div class="clear"></div>

                   <div><label for="comment"><?php echo Mage::helper('contacts')->__('Comment') ?></label></div>
                   <div><textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" style="height:150px;" cols="50" rows="5" placeholder="<?php echo Mage::helper('contacts')->__('Tell us more *') ?>"></textarea>
                </div>
                </li>
                </ul>
    </fieldset>
    <div class="a-center bottom-space">
        <p class="required a-right bottom-space"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <input name="hideit" id="hideit" value="" style="display:none !important;" type="text"/>
        <button class="form-button" type="submit"><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></button>
    </div>
</form>
<script type="text/javascript">
    var contactForm = new VarienForm('contactForm', true);
</script>
