<!--[if !IE]>banner-section div start here<![endif]-->

<div class="order-confirmation-sec">
  <div class="thanksyou-sec"> <span><?php echo $this->__('THANK YOU FOR YOUR INQUIRY')?><br/>
    <?php echo $this->__('YEEHAW!')?></span></div>
  <div class="order-confir-sec">
    <div class="order-inner">
      <div class="order-video-sec"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_confirmation_video')->toHtml()?></div>
      <div class="order-video-right">
        <div class="order-contact-sec default-img"> 
        <span class="order-contact-txt"> Contact Us: <span><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('phone_number')->toHtml()?></span> </span> 
       </div>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_confirmation_content')->toHtml()?>
      </div>
    </div>
    
    <div class="order-newsletter-sec">
      <div class="order-newsletter-inner">
        <div class="ordernewsletter-txt"><?php echo $this->__('Newsletter:')?></div>
        <div class="order-newsletter-input">
<!--
          <input name="email" id="email" type="text" value="<?php echo Mage::getSingleton('customer/session')->getPostedEmail();?>"/>
          <span><?php echo $this->__('Enter your Email Address to recieve special offers and promotions!')?></span> </div>
        <img src="<?php echo $this->getSkinUrl('images/subscribe-btn1.png')?>" alt="<?php echo $this->__('Subscribe newsletter')?>"  /> 
-->
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('constantcontact/signup.phtml')->toHtml();?>
        </div>
      <div class="order-follow-inner">
        <div class="ordernewsletter-txt">Follow Us:</div>
        
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('social_media_links')->toHtml()?>
      </div>
    </div>
  </div>
</div>
<!--[if !IE]>banner-section div end here<![endif]-->
