   <div class="giftcard-leftbar">
      <div class="giftcardinner">
        <div class="giftcard-sec"> She’s bold. She’s beautiful. She knows exactly what she wants.
          <p>Show her you love her with a gift certificate that says you know what she wants too. </p>
        </div>
       
       <div class="btn-button buy-btn"><a href="<?php echo Mage::getUrl('gift-certificates.html')?>" title="Gift certificates"><span><span>BUY NOW</span></span></a></div>
        </div>
    </div>
