<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate">
<fieldset class="group-select">
    <legend><?php echo $this->__('Change Account Password') ?></legend>
    <ul>
        <li>
            <div><label for="current_password"><?php echo $this->__('Current Password') ?> <span class="required">*</span></label></div>
            <div class="input-box"><input type="password" class="required-entry input-text" name="current_password" id="current_password" /></div>
        </li>
        <li>
            <div><label for="password"><?php echo $this->__('New Password') ?> <span class="required">*</span></label></div>
            <div class="input-box"><input type="password" class="required-entry validate-password input-text" name="password" id="password" /></div>
            <div><label for="confirmation"><?php echo $this->__('Confirm New Password') ?> <span class="required">*</span></label></div>
            <div class="input-box"><input type="password" class="required-entry validate-cpassword input-text" name="confirmation" id="confirmation" /></div>
        </li>
    </ul>
</fieldset>
<div class="button-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button class="form-button" type="submit"><span><?php echo $this->__('Save Password') ?></span></button>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
</script>
