<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="page-head"><h2><?php echo $this->__('Reset a Password') ?></h2></div>
<div class="login-box">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
        <fieldset>
            <ul class="form-list">
                <li class="fields">
                    <div>
                        <label for="password"><?php echo $this->__('New Password'); ?> <span class="required">*</span></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                        </div>
                    </div>
                    <div>
                        <label for="confirmation"><?php echo $this->__('Confirm New Password'); ?> <span class="required">*</span></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                        </div>
                    </div>
                </li>
                <p class="a-right required"><?php echo $this->__('* Required Fields') ?></p>
                <div class="a-center">
                    <button type="submit" class="form-button right"><span><?php echo $this->__('Submit') ?></span></button><br />
                </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>